name: Run benchmarks

on:
  workflow_dispatch:

env:
  BENCHMARK_ENV: ${{ vars.BENCHMARK_ENV }}
  KAFKA_API_URL: ${{ vars.KAFKA_API_URL }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
        pip install -e .[benchmark]

    - name: Benchmark with pytest
      run: |
        pytest -s -vv ./benchmarks/*
